### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Xerus2000** [stonecrusher/UserCSS-WEBde#1]
Der dark mode ist für meine Verhältnisse etwas zu schwarz und nicht so nett für die Augen. Ich hatte bei mir provisorisch vorher das hinzugefügt, erzeugt ein schönes Grau, allerdings invertiert es auch bei Bildern die Farben:

```
/**** Dark ****/
html.turquoise {
	background: #333;    
}
.atl-navbar {
	background: #edd3;
}
iframe.atl-app-stack__children {
	filter: invert(0.9);
}
```

Vielleicht kann man das irgendwie einarbeiten ;)

**Comment by stonecrusher** [comment]
Danke für die Rückmeldung.

> Der dark mode ist für meine Verhältnisse etwas zu schwarz

Da gebe ich dir Recht. Hatte ich glaube ich so gemacht, damit die invertierten Bilder keinen Rand erzeugen. War insgesamt aber sowieso nicht auf Schönheit getrimmt :-)

Ich habe mal die Standardfarben geändert (dafür sind aber eigentlich auch die Optionen da - entweder direkt im Quelltext oder falls du Stylus verwendest, live im Popup. Ist recht praktisch).
![screenshot 151](https://user-images.githubusercontent.com/1388389/40689091-fa4e4ace-63a0-11e8-90c1-8b845ff52aa6.png)

Die Menüleiste kannst du dir mit `#app-logo ~ atlas-app * { background-color:green  !important; }` umfärben.

Passt so?

Gruß,
Stonecrusher

**Comment by stonecrusher** [comment]
Am Logoutbutton gibt's nicht viel zu fixen, der ist doch gar nicht kaputt.
Habe die Farbe frei wählbar gemacht, meintest du das?

Overlap ist behoben.

**Comment by Xerus2000** [comment]
Das problem ist, dass der logoutbutton beim darkmode halb orange und halb dunkel ist, was etwas seltsam aussieht:
![image](https://user-images.githubusercontent.com/13354331/40731645-cf05a89e-6431-11e8-87b2-87a4a8094b05.png)

Danke für deine schnellen Antworten übrigens ;)

**Comment by stonecrusher** [comment]
Das ist mehr oder weniger Absicht, denn das Orange vollflächig wäre zu grell und dann hast du das Problem, dass innen die Schriftfarbe nicht mehr passt und auch irgendwie passend geändert werden muss.

Schlimmer ist aber, dass der Hintergrund vom Darkstyle überschrieben werden muss. Da der schon mit `!important` eingebaut wird, muss ich mit einer höheren CSS-Spezifität ran und das geht in dem Fall schlecht.
Normal hätte ich einfach irgend eine sinnlose ID davor gestellt, aber leider ist in dem Fall im HTML keine vorhanden.
Der verantwortliche Selektor aus dem Darkstyle ist aber elendig lang und nur mit Klassennamen kaum zu überbieten.

**Comment by stonecrusher** [comment]
Ich habe ein wenig umstrukturiert, die Adressen haben sich geändert.  
Bei weiteren Fragen bitte hier ein neues Issue aufmachen:  
https://github.com/stonecrusher/stylus-UserCSS/issues

Bitte 1x über diesen Link manuell updaten (falls du die UserCSS Version hier von Github beziehst):  
https://raw.githubusercontent.com/stonecrusher/stylus-UserCSS/master/WEBde/webde-geputzt.user.css

Falls du nicht die UserCSS Version hast und kein Stylus benutzt, musst du nichts machen. Es würde außerdem ein Hinweis kommen.
